### ISSUE TITLE
No version argument

### ISSUE THREAD

**Issue by desdrury** [yusufhm/rockpool#4]
`rockpool` does not have a version argument.  This means you need to remember what version you installed so as to know whether to upgrade or not.  Please can a version argument be included?

**Comment by AlexSkrypnyk** [comment]
Also, please make sure to pass the version in CI build so that binaries would have a build version

**Comment by yusufhm** [comment]
`version` command added:
```
$ rockpool version
Version:  0.4.7
Commit:  bd5f8c816a87bcbedfc9ec08229b6ef4bc1e3728
```

**Comment by yusufhm** [comment]
Note: you can also install using Homebrew now:
```
brew install salsadigitalauorg/rockpool/rockpool
```
